/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3e4947",
        "on-primary-fixed": "#00201d",
        "tertiary-fixed": "#ffdbcf",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#ffb690",
        "surface-tint": "#066a61",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffc9b7",
        "secondary": "#9d4300",
        "surface-container-high": "#e6e8ea",
        "outline": "#6e7977",
        "on-secondary-fixed": "#341100",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "primary": "#004e47",
        "on-primary-container": "#93e4d8",
        "inverse-primary": "#85d5c9",
        "secondary-fixed": "#ffdbca",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#8b4b32",
        "tertiary": "#6e341d",
        "primary-fixed-dim": "#85d5c9",
        "on-primary-fixed-variant": "#005049",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "primary-fixed": "#a1f1e5",
        "on-tertiary-fixed-variant": "#71361f",
        "surface-dim": "#d8dadc",
        "outline-variant": "#bec9c6",
        "on-error-container": "#93000a",
        "secondary-container": "#ff8d4b",
        "on-secondary-container": "#6c2c00",
        "on-secondary": "#ffffff",
        "primary-container": "#00685f",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#380d00",
        "tertiary-fixed-dim": "#ffb59a",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
