-- TB_AUCTION_REQ.BUS_CHANG_CNT — 컬럼 주석 적용 ('버스기사변경')
-- 실행 전 타입이 다르면 `SHOW FULL COLUMNS FROM TB_AUCTION_REQ WHERE Field = 'BUS_CHANG_CNT';` 결과에 맞게 INT / UNSIGNED 등을 조정하세요.

ALTER TABLE `TB_AUCTION_REQ`
  MODIFY COLUMN `BUS_CHANG_CNT` INT NOT NULL DEFAULT 0 COMMENT '버스기사변경';
