-- TB_DRIVER_DETAIL: 면허·운수종사 자격 검증용 컬럼 추가
-- 최초 1회 실행 권장. 이미 존재하는 컬럼에 대해 Duplicate column 오류가 나면 해당 줄만 무시하면 된다.
-- (`ensure*` 코드에서는 추가하지 않음 — 운영은 DDL로 반영.)

ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN LICENSE_TYPE VARCHAR(100) NULL COMMENT '면허 종류';
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN LICENSE_NO VARCHAR(100) NULL;
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN LICENSE_SERIAL_NO VARCHAR(100) NULL;
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN LICENSE_ISSUE_DT DATE NULL;
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN LICENSE_EXPIRY_DT DATE NULL;
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN QUAL_CERT_NO VARCHAR(100) NULL;
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN QUAL_CERT_VERIFY_STATUS VARCHAR(30) NULL DEFAULT 'UNVERIFIED';
ALTER TABLE TB_DRIVER_DETAIL ADD COLUMN QUAL_CERT_VERIFY_DT DATETIME NULL;
