-- @deprecated TB_BUS_DRIVER_VEHICLE 로 이전됨. 레거시 TB_DRIVER_BUS 수동 보강 시에만 사용.

ALTER TABLE TB_DRIVER_BUS ADD COLUMN AMENITIES JSON NULL AFTER SERVICE_CLASS;
ALTER TABLE TB_DRIVER_BUS ADD COLUMN HAS_ADAS CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ADAS Y/N' AFTER AMENITIES;
ALTER TABLE TB_DRIVER_BUS ADD COLUMN VEHICLE_PHOTOS_JSON JSON NULL COMMENT '차량 사진 FILE_UUID 배열' AFTER INS_CERT_FILE_UUID;
