-- TB_AUCTION_REQ_VIA — 견적 요청 상세 경로 (Waypoints)
-- 여정의 시작점부터 끝점까지 모든 지점을 타입별로 순차 저장합니다.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_AUCTION_REQ_VIA` (
  `VIA_UUID`        BINARY(16)     NOT NULL,
  `REQ_UUID`        BINARY(16)     NOT NULL COMMENT 'TB_AUCTION_REQ.REQ_UUID 참조',
  `VIA_ORD`         INT            NOT NULL COMMENT '방문 순서 (1부터 시작하는 일련번호)',
  `VIA_ADDR`        VARCHAR(255)   NOT NULL COMMENT '상세 주소',
  `VIA_TYPE`        ENUM('START_NODE', 'START_WAY', 'ROUND_TRIP', 'END_WAY', 'END_NODE') NOT NULL COMMENT '지점 구분 (START_NODE: 출발, START_WAY: 가는길경유, ROUND_TRIP: 목적지/회차지, END_WAY: 오는길경유, END_NODE: 최종도착)',
  `STOP_TIME_MIN`   INT            DEFAULT 0 COMMENT '해당 지점에서의 체류 예정 시간(분)',
  `REG_DT`          DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID`          VARCHAR(30)    DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT`          DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID`          VARCHAR(30)    DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`VIA_UUID`),
  KEY `IDX_VIA_REQ` (`REQ_UUID`),
  KEY `IDX_VIA_ORD` (`REQ_UUID`, `VIA_ORD`),
  CONSTRAINT `FK_VIA_MASTER` FOREIGN KEY (`REQ_UUID`) REFERENCES `TB_AUCTION_REQ` (`REQ_UUID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='견적 요청 상세 경로 및 경유기 정보';
