-- TB_AUCTION_REQ_BUS — 견적 요청 차량 상세 (Detail)
-- TB_BUS_RESERVATION.REQ_BUS_UUID → 본 테이블 REQ_BUS_UUID
-- server.js 견적 등록 시 INSERT: REQ_BUS_UUID, REQ_UUID, BUS_TYPE_CD, REQ_AMT, REG_DT, REG_ID
-- POST /api/auction/cancel-bus: REQ_STAT = CANCELED

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_AUCTION_REQ_BUS` (
  `REQ_BUS_UUID`            BINARY(16)     NOT NULL COMMENT 'TB_AUCTION_REQ_BUS 의 고유 키값',
  `REQ_UUID`                BINARY(16)     NOT NULL COMMENT '요청버스의 원 예약요청 키값',
  `BUS_TYPE_CD`             VARCHAR(30)    NOT NULL COMMENT '차량 유형 (TB_COMMON_CODE 참조)',
  `REQ_AMT`                 DECIMAL(18,3)  NOT NULL DEFAULT 0.000 COMMENT '해당 유형·대수 기준 요청 금액(원) (API INSERT 사용)',
  `RES_FEE_TOTAL_AMT`       DECIMAL(18,3)  DEFAULT NULL COMMENT '예약금액 전체 6.6% 해당 금액',
  `RES_FEE_REFUND_AMT`      DECIMAL(18,3)  DEFAULT NULL COMMENT '예약 환급 금액 5.5% 해당 금액',
  `RES_FEE_ATTRIBUTION_AMT` DECIMAL(18,3)  DEFAULT NULL COMMENT '예약 귀속 금액 1.1% 해당 금액',
  `REG_DT`                  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID`                  VARCHAR(30)    DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT`                  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID`                  VARCHAR(30)    DEFAULT NULL COMMENT '수정자 ID',
  `DATA_STAT`               ENUM('AUCTION','BIDDING','CONFIRM','DONE','TRAVELER_CANCEL','DRIVER_CANCEL','CANCELED') NOT NULL DEFAULT 'AUCTION' COMMENT '차량별 상태 (CANCELED: 해당 차량만 취소 등)',
  PRIMARY KEY (`REQ_BUS_UUID`),
  KEY `IDX_REQ_BUS_REQ` (`REQ_UUID`),
  KEY `IDX_REQ_BUS_DATA_STAT` (`DATA_STAT`),
  CONSTRAINT `FK_REQ_BUS_MASTER` FOREIGN KEY (`REQ_UUID`) REFERENCES `TB_AUCTION_REQ` (`REQ_UUID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='견적 요청 차량 상세 (Detail)';
