-- TB_BUS_DRIVER_VEHICLE — 기사 보유 버스 마스터 (버스정보 등록·ADAS·서류 FK)
-- 구 테이블명: TB_DRIVER_BUS (PK BUS_UUID). 신규는 BUS_ID 로 통일.
-- 서버: ensureTbBusDriverVehicleSchema (server.js)

CREATE TABLE IF NOT EXISTS TB_BUS_DRIVER_VEHICLE (
    BUS_ID BINARY(16) NOT NULL PRIMARY KEY COMMENT '버스 고유 ID',
    USER_UUID BINARY(16) NOT NULL COMMENT '소유 기사 (TB_USER)',
    VEHICLE_NO VARCHAR(20) NOT NULL COMMENT '차량 번호',
    MODEL_NM VARCHAR(100) NOT NULL COMMENT '모델명',
    MANUFACTURE_YEAR VARCHAR(10) NULL COMMENT '제작 연도(표시 문자열)',
    MILEAGE INT DEFAULT 0 COMMENT '주행거리 km',
    SERVICE_CLASS VARCHAR(50) NOT NULL COMMENT 'TB_COMMON_CODE BUS_TYPE DTL_CD',
    AMENITIES JSON NULL COMMENT '편의 옵션 JSON (wifi, usb, …)',
    HAS_ADAS CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ADAS Y/N',
    LAST_INSPECT_DT DATE NULL COMMENT '최근 정기점검일',
    INSURANCE_EXP_DT DATE NULL COMMENT '보험 만료 예정일',
    BIZ_REG_FILE_UUID BINARY(16) NULL,
    TRANS_LIC_FILE_UUID BINARY(16) NULL,
    INS_CERT_FILE_UUID BINARY(16) NULL,
    VEHICLE_PHOTOS_JSON JSON NULL COMMENT '차량 사진 FILE_UUID 배열(최대 8)',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_VEHICLE_NO (VEHICLE_NO),
    KEY IDX_BUS_DRIVER_USER (USER_UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='기사 보유 차량·ADAS·서류';
