-- TB_BUS_DRIVER_VEHICLE_FILE_HIST — 차량 서류·사진 업로드 이력
-- Requires: TB_BUS_DRIVER_VEHICLE, TB_FILE_MASTER
-- 구명: TB_DRIVER_BUS_FILE_HIST (컬럼 BUS_UUID → BUS_ID)

CREATE TABLE IF NOT EXISTS TB_BUS_DRIVER_VEHICLE_FILE_HIST (
    HIST_UUID BINARY(16) NOT NULL PRIMARY KEY,
    BUS_ID BINARY(16) NOT NULL COMMENT 'FK TB_BUS_DRIVER_VEHICLE.BUS_ID',
    FILE_UUID BINARY(16) NOT NULL,
    FILE_CATEGORY VARCHAR(50) NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY IDX_BUS_FILE (BUS_ID, FILE_UUID),
    KEY IDX_FILE_UUID (FILE_UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
