-- TB_CHAT_LOG(방) + TB_CHAT_LOG_HIST(메시지) + TB_CHAT_LOG_PART(참가자) — 정본 3분할
-- • 방 식별자: CHAT_LOG_SEQ (INT AUTO_INCREMENT). 구 CHAT_LOG_UUID(binary(16))·CHAT_SEQ 는 이 컬럼으로 통일.
-- • binary(16) UUID 형 연동 컬럼은 제거: 업무 키는 REQ_ID·RES_ID(varchar), 참가자는 TB_CHAT_LOG_PART.CUST_ID 로 관리.
-- • TB_BUS_RESERVATION 연동: DATA_STAT IN ('BIDDING','CONFIRM') 등은 앱 쿼리 조건. 방 생성 시 RES_ID·REQ_ID 채우고
--   TB_CHAT_LOG_PART 에 DRIVER·TRAVELER(및 추후 PARTNER·EMPL) 행으로 다자 확장.
-- • UK_CHAT_LOG_RES: 예약 미연동 방은 REQ_ID·RES_ID 모두 NULL 허용(MySQL UNIQUE 에서 NULL 는 서로 다른 행 허용).

CREATE TABLE IF NOT EXISTS `TB_CHAT_LOG` (
  `CHAT_LOG_SEQ` int NOT NULL AUTO_INCREMENT COMMENT '대화(방) 일련 — PK',
  `ROOM_KIND` enum('TRAVELER','DRIVER','PARTNER','EMPL','OTHER') NOT NULL COMMENT 'TRAVELER:여행자, DRIVER:버스기사, PARTNER:영업회원, EMPL:관리직원, OTHER:이외',
  `CHAT_TITLE` varchar(200) DEFAULT NULL COMMENT '대화(방) 제목 — 미입력 시 앱에서 REQ/닉 등 합성',
  `CHAT_COVER_FILE_ID` varchar(20) DEFAULT NULL COMMENT '대화창 썸네일 — TB_FILE_MASTER.FILE_ID(선택)',
  `REQ_ID` varchar(10) DEFAULT NULL COMMENT 'TB_AUCTION_REQ — 미연동 시 NULL',
  `RES_ID` varchar(10) DEFAULT NULL COMMENT 'TB_BUS_RESERVATION — 미연동 시 NULL',
  `CREATED_BY_CUST_ID` varchar(10) NOT NULL COMMENT '방 개설자 TB_USER.CUST_ID',
  `LAST_MSG_DT` datetime DEFAULT NULL COMMENT '마지막 메시지 시각(TB_CHAT_LOG_HIST 기준 갱신 권장)',
  `REG_DT` datetime DEFAULT CURRENT_TIMESTAMP,
  `REG_ID` varchar(10) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MOD_ID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`CHAT_LOG_SEQ`),
  UNIQUE KEY `UK_CHAT_LOG_RES` (`REQ_ID`,`RES_ID`),
  KEY `IDX_CHAT_LOG_ROOM_KIND` (`ROOM_KIND`,`REG_DT`),
  KEY `IDX_CHAT_LOG_CREATED` (`CREATED_BY_CUST_ID`,`REG_DT`),
  KEY `IDX_CHAT_LOG_REQ_REG` (`REQ_ID`,`REG_DT`),
  CONSTRAINT `CHK_CHAT_LOG_REQ_RES` CHECK (
    ((`REQ_ID` IS NULL) AND (`RES_ID` IS NULL))
    OR ((`REQ_ID` IS NOT NULL) AND (`RES_ID` IS NOT NULL))
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅 대화(방) 마스터 — 참가자는 TB_CHAT_LOG_PART';


CREATE TABLE IF NOT EXISTS `TB_CHAT_LOG_HIST` (
  `HIST_SEQ` int NOT NULL AUTO_INCREMENT COMMENT '메시지 일련',
  `CHAT_LOG_SEQ` int NOT NULL COMMENT 'TB_CHAT_LOG.CHAT_LOG_SEQ',
  `SENDER_CUST_ID` varchar(10) NOT NULL COMMENT '발신자 TB_USER.CUST_ID',
  `SENDER_ROLE` enum('TRAVELER','DRIVER','PARTNER','EMPL','SYSTEM') NOT NULL COMMENT 'TRAVELER:여행자, DRIVER:버스기사, PARTNER:영업회원, EMPL:관리직원, SYSTEM:시스템',
  `MSG_KIND` varchar(20) NOT NULL DEFAULT 'TEXT',
  `MSG_BODY` text,
  `FILE_ID` varchar(20) DEFAULT NULL COMMENT '첨부 시 TB_FILE_MASTER.FILE_ID',
  `REG_DT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HIST_SEQ`),
  KEY `IDX_HIST_CHAT` (`CHAT_LOG_SEQ`,`REG_DT`),
  KEY `IDX_HIST_SENDER` (`SENDER_CUST_ID`,`REG_DT`),
  CONSTRAINT `FK_HIST_CHAT` FOREIGN KEY (`CHAT_LOG_SEQ`) REFERENCES `TB_CHAT_LOG` (`CHAT_LOG_SEQ`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅 메시지';


CREATE TABLE IF NOT EXISTS `TB_CHAT_LOG_PART` (
  `CHAT_LOG_SEQ` int NOT NULL COMMENT 'TB_CHAT_LOG.CHAT_LOG_SEQ',
  `CUST_ID` varchar(10) NOT NULL COMMENT 'TB_USER.CUST_ID',
  `PART_TYPE` enum('TRAVELER','DRIVER','PARTNER','EMPL') NOT NULL COMMENT '이 방에서의 역할 — 표시·권한',
  `JOINED_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '방 입장(등록) 시각',
  `INVITER_CUST_ID` varchar(10) DEFAULT NULL COMMENT '초대로 입장 시 초대한 CUST_ID — 기사 초대 시 기사 ID',
  PRIMARY KEY (`CHAT_LOG_SEQ`,`CUST_ID`),
  KEY `IDX_PART_CUST` (`CUST_ID`,`CHAT_LOG_SEQ`),
  CONSTRAINT `FK_PART_CHAT` FOREIGN KEY (`CHAT_LOG_SEQ`) REFERENCES `TB_CHAT_LOG` (`CHAT_LOG_SEQ`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅방 참가자(1:N)';
