-- 실시간 채팅 로그 (기사–여행자, 견적 REQ 단위)
-- 조건: TB_AUCTION_REQ.REQ_STAT = 'BIDDING' 이고 TB_BUS_RESERVATION 이 동일 TRAVELER/REQ 로 매칭되며 RES_STAT IN ('REQ','CONFIRM','DONE')

CREATE TABLE IF NOT EXISTS TB_CHAT_LOG (
    CHAT_LOG_UUID BINARY(16) NOT NULL PRIMARY KEY COMMENT '채팅 로그 PK',
    REQ_UUID BINARY(16) NOT NULL COMMENT 'TB_AUCTION_REQ.REQ_UUID',
    RES_UUID BINARY(16) NULL COMMENT 'TB_BUS_RESERVATION.RES_UUID',
    TRAVELER_UUID BINARY(16) NOT NULL COMMENT '여행자 USER_UUID',
    DRIVER_UUID BINARY(16) NOT NULL COMMENT '기사 USER_UUID',
    SENDER_UUID BINARY(16) NOT NULL COMMENT '발신자 USER_UUID',
    SENDER_ROLE ENUM('TRAVELER','DRIVER','SYSTEM') NOT NULL,
    MSG_KIND VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT, IMAGE, FILE, SYSTEM',
    MSG_BODY TEXT NULL COMMENT '본문 또는 시스템 문구',
    FILE_UUID BINARY(16) NULL COMMENT '첨부 시 TB_FILE_MASTER',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY IDX_CHAT_LOG_REQ_REG (REQ_UUID, REG_DT),
    KEY IDX_CHAT_LOG_DRIVER (DRIVER_UUID, REG_DT),
    KEY IDX_CHAT_LOG_THREAD (REQ_UUID, DRIVER_UUID, TRAVELER_UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='실시간 채팅 로그';

-- 이미 다른 스키마로 TB_CHAT_LOG 가 있으면 `CREATE TABLE IF NOT EXISTS` 는 아무 것도 하지 않습니다.
-- 서버 기동 시 `migrateTbChatLogColumns` (`server.js`) 가 누락 컬럼을 `ALTER TABLE ... ADD COLUMN` 으로 보강합니다.
