-- TB_DRIVER_BUS_FILE_HIST: vehicle document submission history
-- Requires: TB_DRIVER_BUS, TB_FILE_MASTER (InnoDB)

CREATE TABLE IF NOT EXISTS TB_DRIVER_BUS_FILE_HIST (
    HIST_SEQ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'History PK',
    BUS_UUID BINARY(16) NOT NULL COMMENT 'FK TB_DRIVER_BUS.BUS_UUID',
    FILE_CATEGORY VARCHAR(50) NOT NULL COMMENT 'Business_License | Transportation_Business_License | Insurance_Policy',
    FILE_UUID BINARY(16) NOT NULL COMMENT 'FK TB_FILE_MASTER.FILE_UUID',
    REG_USER_UUID BINARY(16) NULL COMMENT 'Uploader USER_UUID',
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Submitted at',
    REMARK VARCHAR(255) NULL COMMENT 'Optional note',
    PRIMARY KEY (HIST_SEQ),
    UNIQUE KEY UK_HIST_FILE_UUID (FILE_UUID),
    KEY IDX_BUS_CAT_REG (BUS_UUID, FILE_CATEGORY, REG_DT),
    KEY IDX_BUS_REG (BUS_UUID, REG_DT),
    CONSTRAINT FK_HIST_BUS FOREIGN KEY (BUS_UUID) REFERENCES TB_DRIVER_BUS (BUS_UUID)
        ON DELETE CASCADE,
    CONSTRAINT FK_HIST_FILE FOREIGN KEY (FILE_UUID) REFERENCES TB_FILE_MASTER (FILE_UUID)
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Vehicle document submission history';
