-- TB_DRIVER_PAYMENT_HIST — 버스기사 월 회비 자동결제 납부 이력
--
-- 관계:
--   · 기사: DRIVER_ID → TB_USER.USER_ID (tb_subscription.sql 과 동일 체계)
--   · 사용 카드: (CARD_CUST_ID, CARD_SEQ) → TB_PAYMENT_CARD(CUST_ID, CARD_SEQ), 카드 행 삭제 시 NULL
--   · CARD_CUST_ID/CARD_SEQ 는 둘 다 NULL 또는 둘 다 NOT NULL 로 넣을 것(반쪽 쌍 금지). DB CHECK 는
--     FK 의 ON DELETE SET NULL 과 동시 사용 불가(MySQL 3823)이므로 앱/배치에서 검증한다.
--   · 앱에서 기사의 CUST_ID 와 카드 소유 CUST_ID 가 동일한지 검증 권장.
--
-- 선행: TB_USER(USER_ID UK), TB_PAYMENT_CARD(CUST_ID, CARD_SEQ)

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_DRIVER_PAYMENT_HIST` (
  `PAY_HIST_SEQ` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '납부 이력 일련번호',
  `DRIVER_ID` VARCHAR(255) NOT NULL COMMENT '기사 TB_USER.USER_ID',
  `CARD_CUST_ID` VARCHAR(10) DEFAULT NULL COMMENT '결제 카드 TB_PAYMENT_CARD.CUST_ID',
  `CARD_SEQ` INT DEFAULT NULL COMMENT '결제 카드 TB_PAYMENT_CARD.CARD_SEQ',
  `BILLING_YYYYMM` VARCHAR(6) NOT NULL COMMENT '청구·귀속 월(YYYYMM), TB_SUBSCRIPTION.YYYYMM과 동일 체계',
  `PAY_AMT` DECIMAL(13,0) NOT NULL COMMENT '청구 금액(원)',
  `PAY_STAT` ENUM('PENDING','SUCCESS','FAILED','REFUNDED','CANCELLED') NOT NULL DEFAULT 'PENDING' COMMENT '결제 상태',
  `PAY_REQ_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '자동결제 요청(시도) 일시',
  `PAY_COMPLETED_DT` DATETIME DEFAULT NULL COMMENT '승인 완료 일시',
  `PG_TXN_ID` VARCHAR(120) DEFAULT NULL COMMENT 'PG 거래·승인 식별자',
  `FAIL_MSG` VARCHAR(500) DEFAULT NULL COMMENT '실패 사유(PG/내부)',
  `CARD_NICKNAME_SNAPSHOT` VARCHAR(50) DEFAULT NULL COMMENT '결제 시점 카드 별칭(카드 삭제·변경 후 조회용)',
  `CARD_LAST_FOUR_SNAPSHOT` CHAR(4) DEFAULT NULL COMMENT '결제 시점 카드 번호 끝 4자리',
  `REG_DT` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID` VARCHAR(10) DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID` VARCHAR(10) DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`PAY_HIST_SEQ`),
  KEY `IDX_DSP_DRIVER_MONTH` (`DRIVER_ID`, `BILLING_YYYYMM`),
  KEY `IDX_DSP_PAY_STAT_REQ` (`PAY_STAT`, `PAY_REQ_DT`),
  KEY `IDX_DSP_CARD_REF` (`CARD_CUST_ID`, `CARD_SEQ`),
  CONSTRAINT `FK_DSP_PAY_USER` FOREIGN KEY (`DRIVER_ID`) REFERENCES `TB_USER` (`USER_ID`),
  CONSTRAINT `FK_DSP_PAY_CARD` FOREIGN KEY (`CARD_CUST_ID`, `CARD_SEQ`) REFERENCES `TB_PAYMENT_CARD` (`CUST_ID`, `CARD_SEQ`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
COMMENT='버스기사 월 회비 자동결제 납부 이력';
