-- @deprecated 운영·신규 구축은 TB_BUS_DRIVER_VEHICLE 사용 (sql/tb_bus_driver_vehicle.sql)
-- 레거시 호환용으로만 유지. PK 명칭: BUS_UUID → 신규 테이블에서는 BUS_ID

CREATE TABLE IF NOT EXISTS TB_DRIVER_BUS (
    BUS_UUID BINARY(16) NOT NULL PRIMARY KEY,
    USER_UUID BINARY(16) NOT NULL,
    VEHICLE_NO VARCHAR(20) NOT NULL UNIQUE,
    MODEL_NM VARCHAR(100) NOT NULL,
    MANUFACTURE_YEAR VARCHAR(10),
    MILEAGE INT DEFAULT 0,
    SERVICE_CLASS VARCHAR(50) NOT NULL,
    AMENITIES JSON,
    HAS_ADAS CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ADAS 장착 여부 Y/N',
    LAST_INSPECT_DT DATE,
    INSURANCE_EXP_DT DATE,
    BIZ_REG_FILE_UUID BINARY(16),
    TRANS_LIC_FILE_UUID BINARY(16),
    INS_CERT_FILE_UUID BINARY(16),
    VEHICLE_PHOTOS_JSON JSON NULL COMMENT '차량 사진 FILE_UUID 문자열 배열(최대 8)',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='[레거시] 기사 보유 차량 — 마이그레이션 대상 TB_BUS_DRIVER_VEHICLE';
