-- TB_DRIVER_FILE_HIST — 기사(USER) 단위 파일 제출 이력 (운송종사자 자격증 등)
-- 선행: TB_FILE_MASTER, TB_USER(또는 TB_DRIVER_INFO) 존재 권장
-- 서버는 `ensureTbDriverFileHistTable` 로 동등 스키마를 자동 생성할 수 있음.

CREATE TABLE IF NOT EXISTS TB_DRIVER_FILE_HIST (
    HIST_SEQ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_UUID BINARY(16) NOT NULL,
    FILE_CATEGORY VARCHAR(50) NOT NULL COMMENT '예: DRIVER_PROFILE_PHOTO, Transport_Workers_Qualification_Information',
    FILE_UUID BINARY(16) NOT NULL,
    REG_USER_UUID BINARY(16) NULL COMMENT '등록 주체(일반적으로 동일 기사 USER_UUID)',
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(255) NULL,
    PRIMARY KEY (HIST_SEQ),
    UNIQUE KEY UK_DFH_FILE_UUID (FILE_UUID),
    KEY IDX_USER_CAT_REG (USER_UUID, FILE_CATEGORY, REG_DT),
    CONSTRAINT FK_DFH_FILE FOREIGN KEY (FILE_UUID) REFERENCES TB_FILE_MASTER (FILE_UUID)
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='기사 파일 제출 이력(자격증 재업로드 시 버전 누적)';
