-- TB_MOM_MEMBER — 기사(CUST_ID) 월별 청약(응찰) 건수 관리
-- TB_USER(CUST_ID)와 조합. 선행: TB_USER 존재.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_MOM_MEMBER` (
  `CUST_ID`       VARCHAR(10)  NOT NULL COMMENT '기사 TB_USER.CUST_ID',
  `YYYYMM`        VARCHAR(6)   NOT NULL COMMENT '월(YYYYMM)',
  `FEE_POLICY`    ENUM('DRIVER','DRIVER_GENERAL','DRIVER_MIDDLE','DRIVER_HIGH') NOT NULL COMMENT '요금·등급 정책',
  `BASIC_CNT`     INT          NOT NULL DEFAULT 0 COMMENT '월 청약 가능 건수(기본)',
  `USE_CNT`       INT          NOT NULL DEFAULT 0 COMMENT '월 사용 건수',
  `REMAINING_CNT` INT          NOT NULL DEFAULT 0 COMMENT '잔여 건수',
  `REG_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID`        VARCHAR(10)  DEFAULT NULL COMMENT '등록자 CUST_ID',
  `MOD_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID`        VARCHAR(10)  DEFAULT NULL COMMENT '수정자 CUST_ID',
  PRIMARY KEY (`CUST_ID`, `YYYYMM`),
  KEY `IDX_MOM_YYYYMM` (`YYYYMM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='기사 월별 청약 건수';
