-- TB_PAYMENT_CARD — 등록 카드 결제 수단 + 자동결제(월 회비) 일정 메타
--
-- 관계: TB_DRIVER_PAYMENT_HIST 는 (CARD_CUST_ID, CARD_SEQ) 복합 FK 로 본 테이블(PK: CUST_ID, CARD_SEQ) 을 참조한다.
-- 선행: TB_USER(CUST_ID PK) — FK 선택

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PAYMENT_CARD` (
  `CUST_ID` varchar(10) NOT NULL COMMENT '카드정보 등록한 사용자 TB_USER.CUST_ID',
  `CARD_SEQ` int NOT NULL COMMENT '사용자의 카드 등록 SEQ',
  `CARD_NICKNAME` varchar(50) DEFAULT NULL COMMENT '카드 별칭',
  `CARD_NO_ENC` varchar(255) NOT NULL COMMENT '카드번호 ENC정보',
  `CARD_BILLING_KEY_ENC` varchar(512) DEFAULT NULL COMMENT 'PG 빌링키·결제토큰 AES-GCM (미사용 시 NULL)',
  `ORIGINAL_CARD_NAME` varchar(50) DEFAULT NULL COMMENT '발급 카드 명칭',
  `EXP_MONTH` char(2) NOT NULL COMMENT '유효기간 월',
  `EXP_YEAR` char(2) NOT NULL COMMENT '유효기간 년도',
  `IS_PRIMARY` enum('Y','N') DEFAULT 'N' COMMENT '메인 카드여부',
  `AUTO_PAY_START_DT` datetime DEFAULT NULL COMMENT '자동결제(월 회비 등) 시작 일시, NULL=이 카드로 자동결제 미등록',
  `AUTO_PAY_END_DT` datetime DEFAULT NULL COMMENT '자동결제 종료 일시, NULL=시작 후 아직 종료 전(진행·중단 처리 시각)',
  `AUTO_PAY_DAY` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '매월 자동결제 처리일(1~31, 기본 1일; 29~31일은 해당 월 일수에 맞게 배치에서 보정)',
  `REG_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID` varchar(10) DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID` varchar(10) DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`CUST_ID`,`CARD_SEQ`),
  KEY `IDX_TPC_CUST_PRIMARY` (`CUST_ID`,`IS_PRIMARY`),
  KEY `IDX_TPC_AUTO_PAY_ACTIVE` (`CUST_ID`,`AUTO_PAY_START_DT`,`AUTO_PAY_END_DT`),
  CONSTRAINT `FK_TPC_USER` FOREIGN KEY (`CUST_ID`) REFERENCES `TB_USER` (`CUST_ID`),
  CONSTRAINT `CHK_TB_PAYMENT_CARD_AUTO_PAY_DAY` CHECK (`AUTO_PAY_DAY` >= 1 AND `AUTO_PAY_DAY` <= 31),
  CONSTRAINT `CHK_TB_PAYMENT_CARD_AUTO_PAY_RANGE` CHECK (
    `AUTO_PAY_END_DT` IS NULL
    OR (
      `AUTO_PAY_START_DT` IS NOT NULL
      AND `AUTO_PAY_END_DT` >= `AUTO_PAY_START_DT`
    )
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='등록된 신용/체크카드 결제 수단';
