-- TB_SUBSCRIPTION — 버스기사 월별 응찰(구독) 관리
-- 선행: TB_USER (USER_ID VARCHAR(255) PK, utf8mb4_0900_ai_ci)
-- DRIVER_ID 는 TB_USER.USER_ID 와 동일 정의(타입·문자셋·콜레이션) — FK 3780 방지

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_SUBSCRIPTION` (
  `DRIVER_ID`     VARCHAR(255) NOT NULL COMMENT '버스기사 TB_USER.USER_ID',
  `YYYYMM`        VARCHAR(6)   NOT NULL COMMENT '월구독년월(YYYYMM)',
  `FEE_POLICY`    ENUM('DRIVER_GENERAL','DRIVER_MIDDLE','DRIVER_HIGH') NOT NULL COMMENT '요금 정책',
  `BASIC_CNT`     INT          NOT NULL DEFAULT 0 COMMENT '월 응찰 가능 건수',
  `USE_CNT`       INT          NOT NULL DEFAULT 0 COMMENT '월 응찰 건수',
  `REMAINING_CNT` INT          NOT NULL DEFAULT 0 COMMENT '응찰 가능 잔여 건수',
  `REG_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID`        VARCHAR(30)  DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID`        VARCHAR(30)  DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`DRIVER_ID`, `YYYYMM`),
  KEY `IDX_SUB_YYYYMM` (`YYYYMM`),
  CONSTRAINT `FK_SUB_USER` FOREIGN KEY (`DRIVER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='버스기사 월별 응찰 관리';
