-- TB_SUBSCRIPTION — 버스기사 월별 응찰(구독) 관리
-- 근거: BusTaams_Project 테이블 설계.md
--   - 본 문서에 "TB_SUBSCRIPTION" 표 블록은 없음.
--   - 동일 문서 §TB_MON_MEMBER 컬럼·타입·ENUM·감사컬럼을 준수(문서 표기는 TB_MON_MEMBER.
--   - §TB_DRIVER_PAYMENT_HIST 비고: 귀속 월은 TB_SUBSCRIPTION.YYYYMM 과 동일 YYYYMM 체계.
--   - §TB_USER: CUST_ID varchar(10) PRI — FK 대상.
-- 선행: TB_USER 존재(CUST_ID PK).

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_SUBSCRIPTION` (
  `DRIVER_ID`     VARCHAR(10)  NOT NULL COMMENT '버스기사 TB_USER.CUST_ID',
  `YYYYMM`        VARCHAR(6)   NOT NULL COMMENT '구독년월(YYYYMM)',
  `FEE_POLICY`    ENUM('DRIVER_GENERAL','DRIVER_MIDDLE','DRIVER_HIGH') NOT NULL COMMENT '요금 정책',
  `BASIC_CNT`     INT          NOT NULL DEFAULT 0 COMMENT '월 응찰 가능 건수',
  `USE_CNT`       INT          NOT NULL DEFAULT 0 COMMENT '월 사용 건수',
  `REMAINING_CNT` INT          NOT NULL DEFAULT 0 COMMENT '잔여 건수',
  `REG_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `REG_ID`        VARCHAR(10)  NULL DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  `MOD_ID`        VARCHAR(10)  NULL DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`DRIVER_ID`, `YYYYMM`),
  KEY `IDX_SUB_YYYYMM` (`YYYYMM`),
  CONSTRAINT `FK_SUB_USER_CUST` FOREIGN KEY (`DRIVER_ID`) REFERENCES `TB_USER` (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='버스기사 월별 응찰 관리';
