-- TB_USER_CANCEL_HIST — 취소 이력(건별 상세). 거래제한 현재값은 TB_USER_CANCEL_MANAGE 참조.
-- TB_USER_CANCEL_MANAGE(USER_UUID, USER_TYPE) 와 복합 FK 로 연결 — 마스터가 없으면 이력을 붙이지 않도록 보장.
-- 취소사유 코드는 TB_COMMON_CODE(GRP_CD/DTL_CD) 와 애플리케이션에서 정합성 검증 (코드 테이블 스키마에 따라 FK 생략 가능).
-- 선행: TB_USER, TB_USER_CANCEL_MANAGE

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_USER_CANCEL_HIST` (
  `HIST_UUID` binary(16) NOT NULL COMMENT '이력 PK (UUID)',
  `USER_UUID` binary(16) NOT NULL COMMENT '대상 고객 TB_USER.USER_UUID',
  `USER_TYPE` enum('TRAVELER','DRIVER','SALES') NOT NULL COMMENT '고객 구분 — TB_USER_CANCEL_MANAGE 와 동일',
  `CANCEL_REASON_GRP_CD` varchar(50) NOT NULL DEFAULT 'CANCEL_REASON' COMMENT '취소사유 공통그룹코드 → TB_COMMON_CODE.GRP_CD',
  `CANCEL_REASON_DTL_CD` varchar(50) NOT NULL COMMENT '취소사유 상세코드 → TB_COMMON_CODE.DTL_CD',
  `CANCEL_REASON_TEXT` text COMMENT '취소사유 상세 내용',
  `REASON_DOC_FILE_NM` varchar(500) DEFAULT NULL COMMENT '취소사유 증빙 제출 서류 파일명',
  `REG_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이력 등록 일시',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '이력 수정 일시',
  `MOD_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`HIST_UUID`),
  KEY `IDX_UCH_USER_TYPE_REG` (`USER_UUID`, `USER_TYPE`, `REG_DT`),
  KEY `IDX_UCH_REASON` (`CANCEL_REASON_GRP_CD`, `CANCEL_REASON_DTL_CD`),
  CONSTRAINT `FK_UCH_MANAGE_PAIR` FOREIGN KEY (`USER_UUID`, `USER_TYPE`) REFERENCES `TB_USER_CANCEL_MANAGE` (`USER_UUID`, `USER_TYPE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='취소 이력(상세)';
