-- TB_USER_CANCEL_MANAGE — 사용자·유형별 취소 누적·거래제한 마스터
-- 한 사용자(USER_UUID)당 역할(USER_TYPE)마다 1행. 취소 건별 상세는 TB_USER_CANCEL_HIST.
-- 거래제한(TRADE_RESTRICT_*) 은 사용자·유형 단위 현재 상태로 본 테이블에서 관리.
-- 선행: TB_USER

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_USER_CANCEL_MANAGE` (
  `USER_UUID` binary(16) NOT NULL COMMENT '대상 고객 TB_USER.USER_UUID',
  `USER_TYPE` enum('TRAVELER','DRIVER','SALES') NOT NULL COMMENT '고객 구분: 여행자·버스기사·영업회원',
  `CANCEL_CNT` int NOT NULL DEFAULT 0 COMMENT '누적 취소 건수(총합·정책에 따라 세부 합과 일치시키거나 별도 집계)',
  `CANCEL_BUS_DRIVER_CNT` int NOT NULL DEFAULT 0 COMMENT '버스기사 누적 취소 건수',
  `CANCEL_TRAVELER_ALL_CNT` int NOT NULL DEFAULT 0 COMMENT '여행자 여행 전체취소 누적 건수',
  `CANCEL_TRAVELER_PARTIAL_BUS_CNT` int NOT NULL DEFAULT 0 COMMENT '여행자 버스 부분 취소 누적 건수',
  `TRADE_RESTRICT_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '거래제한 여부 Y/N',
  `TRADE_RESTRICT_START_DT` datetime DEFAULT NULL COMMENT '거래제한 시작일시',
  `TRADE_RESTRICT_END_DT` datetime DEFAULT NULL COMMENT '거래제한 종료일시',
  `REG_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '마스터 등록 일시',
  `REG_ID` varchar(50) DEFAULT NULL COMMENT '등록자 ID',
  `MOD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '마스터 수정 일시',
  `MOD_ID` varchar(50) DEFAULT NULL COMMENT '수정자 ID',
  PRIMARY KEY (`USER_UUID`, `USER_TYPE`),
  KEY `IDX_UCM_USER` (`USER_UUID`),
  KEY `IDX_UCM_RESTRICT_START` (`TRADE_RESTRICT_START_DT`),
  KEY `IDX_UCM_RESTRICT_END` (`TRADE_RESTRICT_END_DT`),
  CONSTRAINT `FK_UCM_USER` FOREIGN KEY (`USER_UUID`) REFERENCES `TB_USER` (`USER_UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='고객별·유형별 취소 누적·거래제한 마스터';
